### ISSUE TITLE
Template error: FilterError at /accounts/login/

### ISSUE THREAD

**Issue by rob-vandam** [caktus/django-timepiece#771]
I tried Django 1.5 and 1.4, but I always end up with this error:
FilterError at /accounts/login/

[31mParseError: Unrecognised input[39m[31m in [39m/home/rob/uren/uren/static/timepiece/less/fluidoffsetmixin.less[90m on line 554, column 7:[39m
[90m553     .spanX (@index) when (@index > 0) {[39m
554       [7m[31m[1m([22m~".span@{index}") { .span(@index); }[39m[27m
[90m555       .spanX(@index - 1);[39m[0m[0m

Django==1.4
argparse==1.2.1
distribute==0.6.24
django-appconf==0.6
django-bootstrap-toolkit==2.5.6
django-compressor==1.2
django-pagination==1.0.7
django-selectable==0.7.0
django-timepiece==0.9.3
psycopg2==2.5
python-dateutil==1.5
pytz==2012c
six==1.4.1
wsgiref==0.1.2

Any idea?

Rob

**Comment by benzid-wael** [comment]
I have also the same issue, I've node v7.10 and less v1.4.0
