### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by 57even** [caktus/django-timepiece#812]
Are there any plans on making the project available under python 3? Do you have a demo of the project somewhere?

**Comment by rebecca-caktus** [comment]
Python 3 support is added in #814, which has been merged to develop.

We don't host a demo project. However, we do include an [example Django project setup](https://github.com/caktus/django-timepiece/tree/develop/example_project) with [instructions](https://github.com/caktus/django-timepiece/blob/develop/README.rst#installation) on how to set it up.
