### ISSUE TITLE
Issues with the installation

### ISSUE THREAD

**Issue by metzgerd** [caktus/django-timepiece#825]
Hello,

I tried to follow the installation path but had several issues.
The postgres issue I was able to figure out.
But now I'm stuck with:
  File "/usr/local/lib/python2.7/dist-packages/timepiece/utils/mixins.py", line 45, in CommitOnSuccessMixin
    @method_decorator(transaction.commit_on_success)
AttributeError: 'module' object has no attribute 'commit_on_success'

I used pip install django-timepiece

Is there an easy step by step documentation for a newby like me in django?

Would be great.

**Comment by daaray** [comment]
`commit_on_success` was [removed](https://docs.djangoproject.com/en/1.7/topics/db/transactions/#changes-from-django-1-5-and-earlier) in Django 1.8.  

At present, there is no official release of timepiece that supports 1.8; only the `develop` branch presently supports it.
