### ISSUE TITLE
Error on instalation

### ISSUE THREAD

**Issue by juanpex** [caktus/django-timepiece#864]
Running manage.py compress I get this error.

Compressing... CommandError: An error occurred during rendering /Users/jp/dev/git/django-timepiece/timepiece/templates/timepiece/contract/base.html: NameError: #grid > .core > .span is undefined in /Users/jp/dev/git/django-timepiece/timepiece/static/bootstrap/less/navbar.less on line 199, column 3:
198 .navbar-fixed-bottom .container {
199   #grid > .core > .span(@gridColumns);
200 }

**Comment by mimischi** [comment]
I updated lines 194-200 with the following:

`// Reset container width
// Required here as we reset the width earlier on and the grid mixins don't override early enough
.navbar-static-top .container,
.navbar-fixed-top .container,
.navbar-fixed-bottom .container {
  width: (@gridColumnWidth * @gridColumns) + (@gridGutterWidth * (@gridColumns - 1));
}`

This resolved the problem for me and I was able to run the example_project.

**Comment by mimischi** [comment]
On a related note: django-timepiece/example_project/templates/registration/login.html tries to call the URL to "reset_password" on line 15. This doesn't seem to work and will lead to an 500 error when calling the login page. I just removed this call for testing purposes.

**Comment by TaylanT** [comment]
i had the same problems -both solutions from @mimischi worked for me

**Comment by panatale1** [comment]
@juanpex is it safe to close this issue?
