### ISSUE TITLE
Is it Compatible with django 3.x+??

### ISSUE THREAD

**Issue by chilusoft** [caktus/django-timepiece#886]
I would like to know if this project is compatible with the latest version of django(at the time of this writing, its version 3.2). I would like to use it in an existing project

**Comment by mehrabcz** [comment]
i tested on django4.x and it was not compatible

**Comment by panatale1** [comment]
@chilusoft Not as of yet. Compatibility upgrades are in the works

**Comment by chilusoft** [comment]
Well noted.
